bookings/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.booking, name="booking"),
]

contact/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.contact, name="contact"),
]

gallery/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.ImageList.as_view(), name='gallery'),
]

mamaskitchen/urls.py
from django.contrib import admin
from django.urls import path, include
from bookings import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path("", views.home, name='home'),
    path('booking/', include("bookings.urls"), name='booking'),
    path('thanks/', views.thankyou, name='thankyou'),
    path('edit-booking', views.enter_ref_edit, name='enter_ref_edit'),
    path('edit-booking/<booking_ref>',
         views.edit_booking, name='edit-booking'),
    path('accounts/', include('allauth.urls')),
    path('cancel-booking', views.enter_ref_delete, name='enter_ref_delete'),
    path('cancel-booking/<booking_ref>', views.delete_booking, name='cancel'),
    path('cancelled', views.cancelled, name='cancelled'),
    path('menu', views.menu, name='menu'),
    path('privacy-policy', views.privacy, name='privacy'),
    path('contact/', include("contact.urls"), name='contact'),
    path('gallery/', include("gallery.urls"), name='gallery'),
    path('reviews/', include("reviews.urls"), name='reviews'),
]

bookings/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import datetime, date
import random


TIME_CHOICES = (
    ("2 PM", "2 PM"),
    ("3 PM", "3 PM"),
    ("4 PM", "4 PM"),
    ("5 PM", "5 PM"),
    ("6 PM", "6 PM"),
    ("7 PM", "7 PM"),
    ("8 PM", "8 PM"),
)


def create_booking_ref():
    unique_ref = random.randint(10000000, 99999999)
    booking_ref = Booking.objects.values_list('booking_ref')
    for ref in booking_ref:
        if unique_ref == ref:
            unique_ref = random.randint(10000000, 99999999)
    return unique_ref


class Booking(models.Model):
    name = models.CharField(max_length=50, null=False)
    email = models.EmailField(max_length=100)
    phone = models.IntegerField()
    party_size = models.PositiveSmallIntegerField(
        default=1,
        validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
        ]
    )
    date = models.DateField(
        default=datetime.now,
        validators=[
            MinValueValidator(date.today())
        ])
    time = models.CharField(max_length=10, choices=TIME_CHOICES)
    special_occasion = models.CharField(max_length=50, default="No")
    special_requirements = models.CharField(max_length=50, default="None")
    booking_ref = models.CharField(
        max_length=8,
        blank=True,
        unique=True,
        primary_key=True,
        default=create_booking_ref
        )
    confirmed = models.BooleanField(default=False)

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return f"Booking request from {self.name} for {self.party_size} people"

contact/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.PositiveBigIntegerField()
    message = models.TextField(max_length=1000)
    
    def __str__(self):
        return self.email

gallery/models.py
from django.db import models
from cloudinary.models import CloudinaryField


TYPE = ((0, 'Starters'), (1, 'Mains'), (2, 'Dessert'))


class Image(models.Model):
    title = models.CharField(max_length=100, blank=False)
    image = CloudinaryField('image', default='placeholder')
    type = models.IntegerField(choices=TYPE, blank=False, default=0)
    published = models.BooleanField(default=False)

    def __str__(self):
        return self.title

bookings/forms.py
from django import forms
from .models import Booking
from allauth.account.forms import SignupForm


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['name', 'email', 'phone', 'party_size', 'date', 'time',
                  'special_occasion', 'special_requirements', 'booking_ref',]
        widgets = {'booking_ref': forms.HiddenInput(),
                   'date': forms.DateInput(
                    format=('%d/%m/%Y'),
                    attrs={'class': 'form-control',
                           'placeholder': 'Select a date',
                           'type': 'date'}
                    )}


class SignupForm(SignupForm):
    first_name = forms.CharField(max_length=50, label='First name:')
    last_name = forms.CharField(max_length=50, label='Last name:')
    phone = forms.IntegerField(label='Phone No.:')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'] = forms.EmailField(label='Email:')

    def save(self, request):
        user = super(SignupForm, self).save(request)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.phone = self.cleaned_data['phone']
        user.save()
        return user

contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

bookings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import Booking
from .forms import BookingForm


# Home page
def home(request):
    return render(request, 'index.html')


# Thank you page - Shows after successful booking 
def thankyou(request):
    return render(request, 'thankyou.html')


# Cancellation page - Shows afer booking is successfully cancelled
def cancelled(request):
    return render(request, 'cancelled.html')


# Menu page
def menu(request):
    return render(request, 'menu.html')


# Privacy policy page
def privacy(request):
    return render(request, 'privacy.html')


# New booking page
def booking(request):

    if request.method == 'POST':
        booking = BookingForm(request.POST)
        if booking.is_valid():
            if int(request.POST.get('party_size')) > isSpaceAvailable(
                    request.POST.get('date'), request.POST.get('time')):
                messages.add_message(
                    request, messages.ERROR, 'There are no tables available at\
                        this time. Choose another time or date.')
            else:
                booking.save()
                return HttpResponseRedirect('/thanks/')
    else:
        booking = BookingForm()

    return render(request, 'booking.html', {'booking_form': booking})


# Check for available seats - 40 seats available per hour
def isSpaceAvailable(date, time):

    maxSeats = 40
    seatsTaken = 0
    bookings_by_date = Booking.objects.filter(date=date)
    bookings_by_time = bookings_by_date.filter(time=time)
    for booking in bookings_by_time:
        seatsTaken = seatsTaken + booking.party_size
    availableSeats = maxSeats - seatsTaken
    return availableSeats


# Page to enter reference number to edit booking
def enter_ref_edit(request):
    return render(request, 'edit-booking-ref.html')


# Edit booking page
def edit_booking(request, booking_ref):
    booking = get_object_or_404(Booking, booking_ref=booking_ref)
    if request.method == 'POST':
        form = BookingForm(request.POST, instance=booking)
        if form.is_valid():
            form.save()
            return redirect('thankyou')
    else:
        form = BookingForm(instance=booking)
    return render(request, 'edit-booking.html', {'edit_form': form})


# Page to enter reference number to delete booking
def enter_ref_delete(request):
    return render(request, 'delete-booking-ref.html')


# Delete booking page
def delete_booking(request, booking_ref):
    booking = get_object_or_404(Booking, booking_ref=booking_ref)

    if request.method == 'POST':
        booking.delete()
        return redirect('cancelled')

    return render(request, 'cancel-confirmation.html', {'booking': booking})

contact/views.py
from django.shortcuts import render
from .forms import ContactForm


def contact(request):

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'contact-success.html')
    form = ContactForm()

    return render(request, 'contact.html', {'contact_form': form})

gallery/views.py
from django.shortcuts import render
from django.views import generic
from .models import Image


class ImageList(generic.ListView):
    model = Image
    queryset = Image.objects.filter(published=True).order_by("type")
    template_name = 'gallery.html'
    paginate_by = 9

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Mama's Kitchen is a friendly restuarant that server quality, home-cooked food.">
    <meta name="keywords" content="food, restaurant, eating out, kitchen">

    <script src="https://kit.fontawesome.com/c1ba389408.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="icon" type="image/png" href="{% static 'images/mamas-kitchen-icon.png' %}">

    <script src="https://cdn.jsdelivr.net/npm/@emailjs/browser@3/dist/email.min.js">
    </script>
    <script>
        (function () {
            emailjs.init("DX_Uv03oANSKy1cu6");
        })();
    </script>

    <title>Mama's Kitchen</title>

</head>

<body>

    <!-- Header & Navigation -->

    <header>
        <nav class="navbar navbar-expand-sm">
            <div id="nav-container" class="container-fluid bg-nav-container">
                <div class="row align-items-center w-100 justify-content-between">
                    <div class="col-9 col-sm-2 col-md-3">
                        <a class="navbar-brand" href="{% url 'home' %}">
                            <img id="logo" src="{% static 'images/mamas-kitchen-logo.png' %}" alt="Mama's Kitchen logo">
                        </a>
                    </div>

                    <div class="col-3 col-sm-9 col-md-8">
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
                            aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon right"></span>
                        </button>

                        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                            <ul class="navbar-nav me-2 mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link " href="{% url 'menu' %}">Menu</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'gallery' %}">Gallery</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'reviews' %}">Reviews</a>
                                </li>
                                {% if user.is_authenticated %}
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Bookings
                                    </a>
                                    <ul class="dropdown-menu bg-dropdown-menu">
                                        <li><a class="dropdown-item" href="{% url 'booking' %}">New Booking</a></li>
                                        <li><a class="dropdown-item" href="{% url 'enter_ref_edit' %}">Edit Booking</a></li>
                                        <li><a class="dropdown-item" href="{% url 'enter_ref_delete' %}">Cancel Booking</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                                </li>
                                {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'booking' %}">Bookings</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <!-- Messages -->

    <div class="container-fluid bg-nav-container">
        <div class="row">
            <div class="col-md-8 offset-md-2 pt-3">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show bg-message pt-2 border border-dark" 
                    id="msg" role="alert">
                        {{ message | safe }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- Main content -->

    <main>
        {% block content %}

        {% endblock %}
    </main>

    <!-- Footer -->

    <footer id="footer" class="bg-dark container-fluid text-center fixed-bottom">
        <div class="row align-items-center p-3">
            <div class="col-12 col-md-4 text-center text-white">
                <a href="{% url 'contact' %}" class="text-white">Contact Us</a> | <a href="{% url 'privacy' %}" class="text-white">Privacy Policy</a>     
            </div>
            <div class="col-12 col-md-4 text-center text-white">
                See our socials: <a href="https://facebook.com" target="_blank"><i class="fab fa-facebook-square ms-3 orange-text"></i></a>
                <a href="https://twitter.com" target="_blank"><i class="fab fa-twitter-square ms-3 orange-text"></i></a>
                <a href="https://instagram.com" target="_blank"><i class="fab fa-instagram-square ms-3 orange-text"></i></a>
            </div>
            <div class="col-12 col-md-4 text-center text-white">&copy; Mama's Kitchen 2023</div>
        </div>
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
        integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous">
    </script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/sendEmail.js'%}"></script>
</body>

</html>

templates/booking.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<section id="booking-form-section" class="container-fluid">

    <div class="row p-3">
        <div class="col-12 bg-menu-header text-center p-3 border border-dark">
            <small>Mama's Kitchen</small>
            <h1>Book a table</h1>
        </div>
    </div>

    <div class="row pt-3">
        <div class="col-12 col-md-8 offset-md-2">
            <h3 class="uppercase text-center">Want to book a table?</h3>
            <h5 class="text-center">Online bookings are available for parties of up to 10 people.</h5>
            <p class="text-center">If you would like to book a larger table, please <a href="{% url 'contact' %}" class="orange-text">contact us</a> directly.</p>

            <div class="center-form mx-auto p-3">
                <form method="post" onsubmit="return sendMail(this)" class="needs-validation">
                    {% csrf_token %}
                    {{ booking_form | crispy }}
                    <div class="form-row text-center">
                        <div class="col-12 p-2">
                            <button type="submit" class="btn btn-secondary dark-text">Book now!</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/cancelled.html
{% extends "base.html" %}
{% block content %}

<section id="cancellation-confirmed-section" class="margin-header">
    <div class="row">
        <div class="col-md-6 offset-md-3 pt-3 text-center">
            <h3>Cancellation Successful!</h3>
            <p class="pt-3">Your booking has been cancelled successfully.</p>
            <p>If you change your mind, you can rebook the table online (subject to availability)
                 or <a href="#" class="orange-text">contact us</a> directly.</p>
        </div>
    </div>
</section>

{% endblock content %}

templates/contact.html
{% extends "base.html" %} 
{% block content %}
{% load crispy_forms_tags %}

<section id="contact-section" class="container-fluid">
    <div class="row">
        <div class="col-12 text-center p-3">
            <h2>Contact Us</h2>
        </div>

        <div class="col-12 text-center">
            How would you prefer to contact us? <br>
            You can call us, email or get in touch via our contact form or social media profiles.  
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-12 p-3">
            <div class="col-12 text-center">
                <h5>Phone: 053-1234567</h5>
                <h5>Email: info@mamaskitchen.ie</h5>
                <h5>Contact form: </h5>
            </div>

            <div class="center-form mx-auto p-3">
                <form method="post" onsubmit="return sendForm(this)" class="needs-validation">
                    {% csrf_token %}
                    {{ contact_form | crispy }}
                    <div class="form-row text-center">
                        <div class="col-12 p-2">
                            <button type="submit" class="btn btn-secondary dark-text">Contact us!</button>
                        </div>
                    </div>
                </form>
            </div>

            <!-- <div class="center-form mx-auto p-3">
                <form onsubmit="return sendMail(this);">
                    {% csrf_token %}
                    <label for="fullname">Full Name: </label>
                    <input type="text" name="name" id="fullname" class="form-control p-2" required />
                    <label for="emailaddress" class="pt-2">Email: </label>
                    <input type="text" name="emailaddress" id="emailaddress" class="form-control p-2" />
                    <label for="content" class="pt-2">Your message: </label>
                    <textarea name="content" id="content" rows="5" class="form-control p-2" placeholder="How can we help?" 
                    required></textarea>
                    <div class="row text-center">
                        <div class="col p-3">
                            <button type="submit" class="btn btn-secondary dark-text" onclick="return contactSuccess()">Contact us</button>
                        </div>
                    </div>
                </form>
            </div> -->
        </div>
    </div>


</section>

{% endblock %}

templates/delete-booking-ref.html
{% extends "base.html" %}
{% block content %}

<section id="enter-booking-ref" class="container-fluid">
    <div class="row pt-3">
        <div class="col-12 col-md-8 offset-md-2 text-center">
            <h2>Cancel Your Booking</h2>
            <p>To cancel your booking, please enter your booking reference number below.</p>
            <p>You'll find this in your confirmation email.</p>
        </div>
        <div class="center-form mx-auto p-3">
            <form onsubmit="window.open('/cancel-booking/' + booking_ref.value)" class="needs-validation text-center">
                <label for="booking_ref">Booking Reference:</label>
                <input type="number" id="booking_ref" name="booking_ref" minlength="8" maxlength="8">
                <div class="form-row text-center pt-3">
                    <div class="col-12 p-2">
                        <button type="submit" class="btn btn-secondary dark-text">Get my booking</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
</section>

{% endblock content %}

templates/edit-booking-ref.html
{% extends "base.html" %}
{% block content %}

<section id="enter-booking-ref" class="container-fluid">
    <div class="row pt-3">
        <div class="col-12 col-md-8 offset-md-2 text-center">
            <h2>Update Your Booking</h2>
            <p>To amend your booking, please enter your booking reference number below.</p>
            <p>You'll find this in your confirmation email.</p>
        </div>
        <div class="center-form mx-auto p-3">
            <form onsubmit="window.open('/edit-booking/' + booking_ref.value)" class="needs-validation text-center">
                <label for="booking_ref">Booking Reference:</label>
                <input type="number" id="booking_ref" name="booking_ref" minlength="8" maxlength="8">
                <div class="form-row text-center pt-3">
                    <div class="col-12 p-2">
                        <button type="submit" class="btn btn-secondary dark-text">Get my booking</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
</section>

{% endblock content %}

templates/edit-booking.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}

<section id="edit-booking-section" class="container-fluid">
    <div class="row pt-3">
        <div class="col-12 col-md-6 offset-md-3 text-center">
            <h2>Update/Cancel Your Booking</h2>
            <p>To amend your booking, please fill out the form below with your new requirements. <br>
                Or, to cancel your booking, click the "Cancel Booking" button below.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="center-form mx-auto p-3">
                <form method="POST" onsubmit="return sendMail(this)" class="needs-validation">
                    {% csrf_token %}
                    {{ edit_form | crispy }}
                    <div class="form-row text-center">
                        <div class="col-12 p-3">
                            <button type="submit" id="update" class="btn btn-secondary dark-text">Update Booking</button>
                        </div>
                    </div>
                </form>
                <p class="text-center mt-3">Cancel my booking: 
                    <form onsubmit="window.open('/cancel-booking/' + booking_ref.value)" method="POST" class="text-center">
                        {% csrf_token %}
                        {{ booking | crispy }}
                        <button type="submit" class="btn btn-secondary dark-text">Cancel Booking</button>
                    </form>
                </p>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/gallery.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<section id="thankyou-section" class="container-fluid">
    <div class="row p-3">
        <div class="col-12 bg-menu-header text-center p-3 border border-dark">
            <small>Mama's Kitchen</small>
            <h1>Gallery</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for image in image_list %}
                <div class="col-md-4">
                    <div class="card mb-3">
                        <div class="card-header text-center bg-image-title">
                            <p class="no-margin">{{ image.title }}</p>
                        </div>
                        <div class="card-body">
                            <div class="image-container text-center">
                                <img class="card-img-top" src=" {{ image.image.url }}">
                            </div>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>

    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link orange-text">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link orange-text"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}

    <div class="margin-bottom">

    </div>


</section>

{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<section id="main-image-section" class="container-fluid">
    <div class="row">
        <div id="welcome-text" class="col-12 bg-menu-header text-center p-3 border border-dark">
            <h3>Welcome to Mama's Kitchen</h3>
            <p>Quality food at quality prices</p>
        </div>
    </div>
    <div class="col-12 g-0 overflow-hidden position-relative">
        <img id="main-image" class="w-100 min-vh-350" src="{% static 'images/set-table.jpeg' %}" alt="Mama's Kitchen table">
    </div>
</section>

<section id="about-us-section">
    <div class="container-fluid mt-4">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="large-text">A FAMILY FRIENDLY RESTAURANT LOCATED IN THE CENTER OF WEXFORD</h2>
                <hr>
                <p>
                    Mama's Kitchen was founded in 2022 and offers a wide range of quality home-cooked and seasonal
                    dishes.
                </p>
                <p>
                    Whether it's a special occasion or you fancy a night off cooking, Mama's Kitchen provides everything
                    you need.
                </p>
                <p>
                    We also cater for special dietary requirements (allergies, coeliacs, lactose intolerance, IBS and
                    more) - You can note this in your booking and one of our friendly team
                    will get in touch to discuss your needs further.
                </p>
            </div>
        </div>
    </div>
</section>

<hr>

<section id="map-section">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 text-center">
                <h3>Walk-ins welcome!</h3>
            </div>
            <div class="col-12 text-center mx-auto">
                <iframe id="gmap_canvas"
                    src="https://maps.google.com/maps?q=47%20south%20main%20street%20wexford&t=&z=13&ie=UTF8&iwloc=&output=embed"></iframe>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/new-review.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<section id="reviews-section" class="container-fluid">
    <div class="row p-3">
        <div class="col-12 bg-menu-header text-center p-3 border border-dark">
            <small>Mama's Kitchen</small>
            <h1>Reviews</h1>
        </div>
    </div>


    <div class="row p-3">
        <div class="col-12 text-center">
            {% if user.is_authenticated %}

            <div class="center-form mx-auto p-3">
                <p>Please fill out the form below to leave a review. Reviews are published immediately.</p>
                <p>Your username will be displayed below your review.</p>
                <form method="post" class="needs-validation review-form">
                    {% csrf_token %}
                    {{ review_form | crispy }}
                    <div class="form-row text-center">
                        <div class="col-12 p-2">
                            <button type="submit" class="btn btn-secondary dark-text">Submit!</button>
                        </div>
                    </div>
                </form>
            </div>

            {% else %}

            <p><a href="{% url 'account_signup' %}" class="orange-text">Sign up</a> for an account or <a href="{% url 'account_login' %}" class="orange-text">log in here</a> to leave a review.</p>

            {% endif %}
        </div>
    </div>

    <div class="margin-bottom">

    </div>


</section>

{% endblock content %}

templates/thankyou.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<section id="thankyou-section" class="container-fluid">
    <div class="row">
        <div class="col-md-6 offset-md-3 pt-3 text-center">
            <h3>Thanks for booking!</h3>
            <p class="pt-3">You will receive an email shortly confirming receipt of your booking.</p>
            <p>If you don't receive the email in the next 30 minutes, please <a href="#" class="orange-text">contact us</a> directly.</p>
        </div>
    </div>
</section>

{% endblock content %}